<a href="https://colab.research.google.com/github/epjf99-rgb/Entregas/blob/main/transformers2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")

In [ ]:
texto="This is a sentence that has a some tokens that will be managed by tokenizer"

In [ ]:
tokens=tokenizer.tokenize(texto)

In [ ]:
print(tokens)

['this', 'is', 'a', 'sentence', 'that', 'has', 'a', 'some', 'token', '##s', 'that', 'will', 'be', 'managed', 'by', 'token', '##izer']


In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
tokenizer = BertTokenizer.from_pretrained('google-bert/bert-base-uncased')
model = BertModel.from_pretrained("google-bert/bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
input_text = """it seemed to me a little on the sleepy side as far as pacing and level of narrative excitement.
And the Pedro Pascal infatuation, ... which would normally charge this material, is inevitably beginning to pall a bit,
because Pascal stars in everything now"""

In [ ]:
tokenizer(input_text)

{'input_ids': [101, 2009, 2790, 2000, 2033, 1037, 2210, 2006, 1996, 17056, 2217, 2004, 2521, 2004, 15732, 1998, 2504, 1997, 7984, 8277, 1012, 1998, 1996, 7707, 17878, 1999, 27753, 14505, 1010, 1012, 1012, 1012, 2029, 2052, 5373, 3715, 2023, 3430, 1010, 2003, 21268, 2927, 2000, 14412, 2140, 1037, 2978, 1010, 2138, 17878, 3340, 1999, 2673, 2085, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
tokenizer(input_text, return_tensors="pt")

{'input_ids': tensor([[  101,  2009,  2790,  2000,  2033,  1037,  2210,  2006,  1996, 17056,
          2217,  2004,  2521,  2004, 15732,  1998,  2504,  1997,  7984,  8277,
          1012,  1998,  1996,  7707, 17878,  1999, 27753, 14505,  1010,  1012,
          1012,  1012,  2029,  2052,  5373,  3715,  2023,  3430,  1010,  2003,
         21268,  2927,  2000, 14412,  2140,  1037,  2978,  1010,  2138, 17878,
          3340,  1999,  2673,  2085,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
tokenizer(input_text,return_tensors="tf")

{'input_ids': <tf.Tensor: shape=(1, 55), dtype=int32, numpy=
array([[  101,  2009,  2790,  2000,  2033,  1037,  2210,  2006,  1996,
        17056,  2217,  2004,  2521,  2004, 15732,  1998,  2504,  1997,
         7984,  8277,  1012,  1998,  1996,  7707, 17878,  1999, 27753,
        14505,  1010,  1012,  1012,  1012,  2029,  2052,  5373,  3715,
         2023,  3430,  1010,  2003, 21268,  2927,  2000, 14412,  2140,
         1037,  2978,  1010,  2138, 17878,  3340,  1999,  2673,  2085,
          102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 55), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 55), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
tf_tokens = tokenizer(input_text,return_tensors="tf")
print(tf_tokens['input_ids'])

tf.Tensor(
[[  101  2009  2790  2000  2033  1037  2210  2006  1996 17056  2217  2004
   2521  2004 15732  1998  2504  1997  7984  8277  1012  1998  1996  7707
  17878  1999 27753 14505  1010  1012  1012  1012  2029  2052  5373  3715
   2023  3430  1010  2003 21268  2927  2000 14412  2140  1037  2978  1010
   2138 17878  3340  1999  2673  2085   102]], shape=(1, 55), dtype=int32)


In [ ]:
embedding = model(**tf_tokens)

AttributeError: EagerTensor object has no attribute 'size'. 
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior()
      

In [ ]:
pt_tokens = tokenizer(input_text, return_tensors="pt")

In [ ]:
import torch
with torch.no_grad():
    outputs = model(**pt_tokens) #El modelo va a generar embedding
    last_hidden_states = outputs.last_hidden_state #C
print("Token embeddings:") #D
for token_id, embedding in zip(pt_tokens["input_ids"][0], last_hidden_states[0]):
    word = tokenizer.decode(int(token_id))
    print(f"{word}: {embedding[:5]}") # Print only the first 5 elements of the embedding for brevity

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


Token embeddings:
[CLS]: tensor([ 0.1211, -0.1653,  0.0349, -0.5464, -0.2400])
it: tensor([-0.2131, -0.2954, -1.0838,  0.3224,  0.1645])
seemed: tensor([-0.3831, -0.0061, -0.5679,  0.1176, -0.0427])
to: tensor([ 0.6556,  0.3458,  0.1800, -0.8581,  0.0035])
me: tensor([ 0.2063, -0.3928,  0.6495, -0.3761, -0.5129])
a: tensor([-0.5579, -0.6557, -0.2146,  0.2590,  0.2975])
little: tensor([-0.5898, -0.3707,  0.1866,  0.2697, -0.2535])
on: tensor([-1.1539, -0.4191,  0.0234, -0.4769,  0.0837])
the: tensor([-1.0409, -0.3491, -0.1922, -0.0040, -0.0330])
sleepy: tensor([-0.9047,  0.0680,  1.1432,  0.0133,  1.1094])
side: tensor([-0.6162, -0.3821,  0.3799,  0.2507, -0.3371])
as: tensor([-1.2451, -0.7362,  0.1051, -0.3538,  0.7928])
far: tensor([-0.8046,  0.6606, -0.5919, -1.0274, -0.3666])
as: tensor([-1.0093,  0.1752, -0.2001,  0.1959, -0.4310])
pacing: tensor([-0.1418,  0.2377, -0.0015,  0.1954, -0.3426])
and: tensor([-0.4684,  0.3706, -0.1120,  0.2505, -0.4568])
level: tensor([-0.1062,  0.2009

In [ ]:
# Convert the PyTorch code to TensorFlow
import tensorflow as tf

# Get the model output using TensorFlow tensors
outputs_tf = tf_model(**tf_tokens)

# Extract the last hidden states
last_hidden_states_tf = outputs_tf.last_hidden_state

print("Token embeddings (TensorFlow):")
# Iterate and print embeddings
# Using tf.gather to get the embedding for each token ID
for i, token_id in enumerate(tf_tokens["input_ids"][0]):
    word = tokenizer.decode(int(token_id.numpy())) # Convert tensor to numpy for decode
    embedding = last_hidden_states_tf[0, i, :5] # Select the embedding and the first 5 elements
    print(f"{word}: {embedding.numpy()}") # Convert tensor to numpy for printing

Token embeddings (TensorFlow):
[CLS]: [ 0.12113444 -0.16532747  0.03492671 -0.54643965 -0.23999265]
it: [-0.21306914 -0.29539058 -1.083801    0.32234976  0.1644648 ]
seemed: [-0.38312432 -0.00607799 -0.56787276  0.11757125 -0.04267798]
to: [ 0.6556278   0.34575242  0.18004668 -0.8580846   0.00347241]
me: [ 0.20630908 -0.39277947  0.64952123 -0.37610194 -0.51286185]
a: [-0.5579139  -0.6557047  -0.21462487  0.2589937   0.29745686]
little: [-0.58978885 -0.370661    0.1865699   0.2697314  -0.25347844]
on: [-1.1538576  -0.41908124  0.02342961 -0.47685406  0.08368276]
the: [-1.0408959  -0.34911656 -0.19219604 -0.00396679 -0.03302685]
sleepy: [-0.9046517   0.06796799  1.1431999   0.01327166  1.1093959 ]
side: [-0.6162286  -0.38214335  0.37987837  0.25073028 -0.33708456]
as: [-1.245073   -0.7361551   0.10512277 -0.35375246  0.79278255]
far: [-0.8046364   0.660567   -0.5918777  -1.0273798  -0.36658582]
as: [-1.0093503   0.17520455 -0.20008114  0.19591987 -0.43095997]
pacing: [-0.14178199  0.237

In [ ]:
from transformers import TFBertModel

tf_model = TFBertModel.from_pretrained("google-bert/bert-base-uncased")

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were 

In [ ]:
from transformers import pipeline

pipe = pipeline("text-classification", model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu


In [ ]:
input = """it seemed to me a little on the sleepy side as far as pacing and level of narrative excitement.
And the Pedro Pascal infatuation, ... which would normally charge this material, is inevitably beginning to pall a bit,
because Pascal stars in everything now
"""

In [ ]:
pipe(input)

[{'label': 'NEGATIVE', 'score': 0.9930942058563232}]

In [ ]:
# task text-classification
# model huaen/question_detection
pipe = pipeline(task="text-classification", model="huaen/question_detection")

config.json:   0%|          | 0.00/853 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/433M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/320 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu


In [ ]:
question="What is the meaning of life and the Universe?"

In [ ]:
pipe(question)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


[{'label': 'question', 'score': 0.9756181836128235}]

In [ ]:
noquestion="Love is all your need"

In [ ]:
pipe(noquestion)

[{'label': 'non_question', 'score': 0.9997580647468567}]

In [ ]:
pipe(noquestion)

[{'label': 'non_question', 'score': 0.9997580647468567}]

In [ ]:
without_questionmark="will ithain tomorrow?"

In [ ]:
pipe(without_questionmark)

[{'label': 'non_question', 'score': 0.8873010277748108}]

# Classify language

In [ ]:
pipe = pipeline("text-classification", model="papluca/xlm-roberta-base-language-detection")

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/502 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Device set to use cpu


In [ ]:
pipe("Frase en Español")

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


[{'label': 'es', 'score': 0.9751560091972351}]

In [ ]:
pipe("我妈妈宠坏了我")

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


[{'label': 'zh', 'score': 0.9818673133850098}]

In [ ]:
pipe("ma mère me gâte")

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


[{'label': 'fr', 'score': 0.9936059713363647}]

In [ ]:
pipe("母は私を甘やかしてくれる")

[{'label': 'ja', 'score': 0.9933680891990662}]

# Spam classifier







In [ ]:
pipe=pipeline("text-classification",model="Delphia/twitter-spam-classifier")

config.json:   0%|          | 0.00/860 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

Device set to use cpu


In [ ]:
spam="""Deposit Successfully Processed!
Account credited with GBP450 - real cash. You can use it for bonus play or other options. Get moving at
Start now!

@ 2024 RedotPlay.com, All Rights Reserved line """

In [ ]:
pipe(spam)

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)


[{'label': 1, 'score': 0.7912172675132751}]

In [ ]:
spam="""Hi Peralta (@Javier9999),

We noticed a new login to your HF account. Here are the details:

Location: Mexico, Mexico City (Approximate location)
Time: 5 Aug 2025 01:47 AM..AM UTC

If you logged in to your account recently, there's nothing for you to do right now.

If you don't recognize this login, we recommend you change your password to a strong one you haven't used before by clicking here. You can also reply to this email directly if you need further assistance.

Cheers,

The Hugging Face team"""